# ── Sentinel types ──────────────────────────────────────────────────
# These replace Union{T, Nothing} patterns throughout the codebase,
# enabling dispatch instead of runtime nothing-checks.

"""Sentinel indicating no population size constraint (infinite population)."""
struct NoPopulation end

"""Sentinel indicating no attributes function is provided."""
struct NoAttributes end

"""Sentinel indicating no type labels for multi-type models."""
struct NoTypeLabels end

"""Sentinel indicating no age distribution is provided."""
struct NoAgeDistribution end

"""Sentinel indicating no case cap for extinction/containment checks."""
struct NoCases end

"""Sentinel indicating no generation time distribution. Used by
[`BranchingProcess`](@ref) for pure chain-statistics models where
timing is irrelevant."""
struct NoGenerationTime end

# Abstract supertype for clinical-state transitions (defined here so
# `SimulationState` can hold a typed `transitions` vector without
# forward-reference issues). Implementations live in
# `src/transitions/`.
abstract type AbstractClinicalTransition end

# ── Transmission models ─────────────────────────────────────────────

"""
Abstract supertype for transmission models. A concrete subtype defines
the latent dynamics; see `models/branching_process.jl` for the
canonical implementation and the [Extending guide](@ref "Extending
EpiBranch") for the protocol new subtypes must implement.
"""
abstract type TransmissionModel end

"""Interface methods with defaults for any TransmissionModel."""
population_size(::TransmissionModel) = NoPopulation()

"""
    single_type_offspring(model::TransmissionModel)

Extract the offspring specification from a single-type transmission
model. Returns whatever the model stores in `offspring` (typically a
`Distribution`, but can also be any type for which
`chain_size_distribution` is defined — e.g. `ClusterMixed`).

This is the canonical extension point for custom transmission models:
analytical helpers (`extinction_probability`, `epidemic_probability`,
`probability_contain`, `proportion_transmission`,
`chain_size_distribution`) all route through it. A new
`<: TransmissionModel` type that defines a method here gets all of
those helpers for free.

Throws for multi-type (function-based) offspring, which the single-type
accessor cannot sensibly return.
"""
function single_type_offspring(model::TransmissionModel)
    hasproperty(model, :offspring) || throw(ArgumentError(
        "$(typeof(model)) has no `offspring` field — did you forget to specialise single_type_offspring for it?"))
    off = model.offspring
    off isa Function && throw(ArgumentError(
        "This function only works with single-type models (not multi-type function offspring)"))
    return off
end
n_types(::TransmissionModel) = 1

# ── Individual state ────────────────────────────────────────────────

"""
A single contact in the transmission tree (infected or not).

Core fields (used by the engine):

- `id`, `parent_id`, `generation`, `chain_id` — identity and position in
  the tree. `id` is the 1-based index into `state.individuals`; this
  invariant is relied on for O(1) parent lookups.
- `infection_time::T` — time at which this contact was exposed.
- `susceptibility::T` ∈ `[0, 1]` — per-contact probability of
  being infected given exposure. Applied as a built-in competing risk
  by the engine during infection resolution.
- `infectiousness::T` ∈ `[0, 1]` — multiplicative modifier on
  this individual's onward transmission, applied when they become a
  parent.

The timing and hazard fields share a real element type `T` (`Float64` by
default). Under automatic differentiation the whole run carries a dual
type, so a gradient flows through the timing parameters; ids and counts
stay `Int`.
- `secondary_case_ids::Vector{Int}` — ids of contacts (infected and
  uninfected) generated by this individual.

`state::Dict{Symbol, Any}` holds everything else: clinical state
(`:onset_time`, `:asymptomatic`), demographics (`:age`, `:sex`),
intervention state (`:isolated`, `:traced`, `:quarantined`,
`:vaccinated`, `:test_positive`, `:type`), the `:infected` flag, and
any user-defined fields.

# Setting fields at simulation time

Pass an `attributes` function to [`simulate`](@ref). It runs on every
new individual at creation. EpiBranch provides builders for clinical
presentation, demographics, and transmission traits, layered with
[`compose`](@ref):

```julia
attributes = compose(
    clinical_presentation(incubation_period = LogNormal(1.6, 0.5)),
    demographics(age_distribution = Uniform(0, 90)),
    transmission_traits(susceptibility = 0.3, infectiousness = 0.9),
)
```

For fields without a dedicated builder, write your own closure
`(rng, ind) -> ...` and `compose` it with the others.

See also [`compose`](@ref), [`clinical_presentation`](@ref),
[`demographics`](@ref), [`transmission_traits`](@ref).
"""
mutable struct Individual{T <: Real}
    id::Int
    parent_id::Int
    generation::Int
    chain_id::Int
    infection_time::T
    susceptibility::T
    infectiousness::T
    secondary_case_ids::Vector{Int}
    state::Dict{Symbol, Any}
end

function Individual(; id::Int, parent_id::Int = 0, generation::Int = 0,
        chain_id::Int = 1, infection_time::Real = 0.0,
        susceptibility::Real = 1.0, infectiousness::Real = 1.0,
        state::Dict{Symbol, Any} = Dict{Symbol, Any}())
    T = promote_type(typeof(infection_time), typeof(susceptibility),
        typeof(infectiousness))
    Individual{T}(id, parent_id, generation, chain_id, convert(T, infection_time),
        convert(T, susceptibility), convert(T, infectiousness), Int[], state)
end

# ── Simulation state ───────────────────────────────────────────────

"""
State of a running or completed simulation.

`transitions` is the per-run vector of clinical transitions (set by
`simulate`). It is held on the state so individual-creation paths can
apply transitions without threading a parameter through every signature.
"""
mutable struct SimulationState{T <: Real, R <: AbstractRNG, P, A}
    individuals::Vector{Individual{T}}
    active_ids::Vector{Int}
    current_generation::Int
    rng::R
    cumulative_cases::Int
    extinct::Bool
    population_size::P
    max_infection_time::T
    attributes::A
    transitions::Vector{AbstractClinicalTransition}
end

"""The real element type carrying timing and hazard values in `state`
(`Float64` by default; a dual type under automatic differentiation)."""
_timetype(::SimulationState{T}) where {T} = T

function Base.show(io::IO, s::SimulationState)
    status = s.extinct ? "extinct" : "active"
    print(io,
        "SimulationState(cases=$(s.cumulative_cases), individuals=$(length(s.individuals)), gen=$(s.current_generation), $(status))")
end
